Correo_Post_Videotutorial_NetCore/Models/Correo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Correo_Post_Videotutorial_NetCore.Models
{
    public class Correo
    {
        public string Destinatario{ get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; } 
    }
}

Correo_Post_Videotutorial_NetCore/Models/ErrorViewModel.cs
using System;

namespace Correo_Post_Videotutorial_NetCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Correo_Post_Videotutorial_NetCore/Controllers/CorreosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Correo_Post_Videotutorial_NetCore.Models;
using Correo_Post_Videotutorial_NetCore.Helpers;

namespace Correo_Post_Videotutorial_NetCore.Controllers
{
    public class CorreosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        private HelperMail helpermail;
        public CorreosController(HelperMail helpermail)
        {
            this.helpermail = helpermail;
        }
        [HttpPost]
        public IActionResult Index(string receptor, string asunto, string texto)
        {
            string mensajefinal = "<h1>Proyecto Techclub Tajamar(MVC NetCore Correos)<h1/><h4>" + texto + " <h4/>"
                                    ; 
            this.helpermail.SendMail(receptor, asunto, mensajefinal);
            ViewData["MENSAJE"] = "Mensaje enviado a '" + receptor + "'";
            return View();
        }
    }
}

Correo_Post_Videotutorial_NetCore/Controllers/HomeController.cs
using Correo_Post_Videotutorial_NetCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Correo_Post_Videotutorial_NetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Correo_Post_Videotutorial_NetCore/Views/Correos/Index.cshtml
<h1>Enviar correos electrónicos</h1>

<form method="post">
    <label>Destinatario: </label>
    <input type="email" class="form-control" name="receptor" placeholder="Ejemplo: 'alguien@correo.com'" required/>
    <br />
    <label>Asunto: </label>
    <input type="text" class="form-control" name="asunto" placeholder="Asunto" required/>
    <br />
    <label>Mensaje:</label>
    <textarea name="texto" class="form-control" placeholder="Escribe tu mensaje"></textarea>
    <br />
    <button type="submit" class="btn btn-success">
        Enviar correo
    </button>
</form>

<h1 style="color:red">@ViewData["MENSAJE"]</h1>

Correo_Post_Videotutorial_NetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenidos a mi aplicación web</h1>
    <p>Para enviar un correo pulsa en el menu principal "correo"</p>
    <p>Para más informacion sobre <a href="https://docs.microsoft.com/aspnet/core"> ASP.NET Core</a>.</p>
</div>

Correo_Post_Videotutorial_NetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Correo NetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:grey">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Enviar Correos NetCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Correos" asp-action="Index">Correo</a>
        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div style="background-color:beige" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Correo_Post_Videotutorial_NetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>